spring:
  datasource:
    driver-class-name: com.taosdata.jdbc.TSDBDriver
    url: jdbc:TAOS://192.168.0.232:6030/test?user=root&password=taosdata

dream:
  toSQL: com.dream.tdengine.sql.ToTdEngine
  listeners:
    - com.dream.drive.listener.DebugListener
